const recipes = {
	"gingerSoyChicken" : {
		name: "Ginger Soy Chicken",
		id: "gingerSoyChicken",
		imgSrc: "images/chicken.jpg",
		cookTime: "30 minutes",
		calories: "600 calories",
		tags: ["","Asian","Cheap"]},
	"garlicRoastedBroccoli" : {
		name: "Garlic Roasted Broccoli",
		id: "garlicRoastedBroccoli",
		imgSrc: "images/garlicRoastedBroccoli.jpg",
		cookTime: "20 minutes",
		calories: "150 calories",
		tags: ["","Vegetarian"]},
	"squashTaco" : {
		name: "Roasted Butternut Squash Tacos",
		id: "squashTaco",
		imgSrc: "images/squashTaco.jpg",
		cookTime: "50 minutes",
		calories: "400 calories",
		tags: ["","Mexican","Vegetarian","Cheap"]},
	"shrimpSoup" : {
		name: "Shrimp Tomato Soup",
		id: "shrimpSoup",
		imgSrc: "images/shrimpSoup.jpg",
		cookTime: "50 minutes",
		calories: "520 calories",
		tags: ["","Fusion"]},
	"porkChop" : {
		name: "Cinnamon Chipotle Pork Chops",
		id: "porkChop",
		imgSrc: "images/porkChop.jpg",
		cookTime: "25 minutes",
		calories: "800 calories",
		tags: ["","Mexican","Fusion"]},
	"tacoSalad" : {
		name: "Taco Salad",
		id: "tacoSalad",
		imgSrc: "images/tacoSalad.jpg",
		cookTime: "30 minutes",
		calories: "450 calories",
		tags: ["", "Mexican", "Cheap"]},
	"spaghettiMeatballs" : {
		name: "Spaghetti and Meatballs",
		id: "spaghettiMeatballs",
		imgSrc: "images/spaghettiMeatballs.jpg",
		cookTime: "30 minutes",
		calories: "660 calories",
		tags: [""]},
	"grilledChicken" : {
		name: "Grilled Chicken Breast",
		id: "grilledChicken",
		imgSrc: "images/grilledChicken.jpg",
		cookTime: "20 minutes",
		calories: "240 calories",
		tags: ["", "Cheap", "Healthy"]},
	"vegeLoMein" : {
		name: "Vegetable Lo Mein",
		id: "vegeLoMein",
		imgSrc: "images/vegeLoMein.jpg",
		cookTime: "15 minutes",
		calories: "170 calories",
		tags: ["", "Vegetarian", "Asian"]},
	"teriyakiBeef" : {
		name: "Teriyaki Beef",
		id: "teriyakiBeef",
		imgSrc: "images/teriyakiBeef.jpg",
		cookTime: "25 minutes",
		calories: "520 calories",
		tags: ["", "Asian"]},
	"chickenNoodleSoup" : {
		name: "Chicken Noodle Soup",
		id: "chickenNoodleSoup",
		imgSrc: "images/chickenNoodleSoup.jpg",
		cookTime: "30 minutes",
		calories: "160 calories",
		tags: ["", "Healthy", "Cheap"]},
	"whiteRice" : {
		name: "White Rice",
		id: "whiteRice",
		imgSrc: "images/whiteRice.jpg",
		cookTime: "20 minutes",
		calories: "125 calories",
		tags: ["", "Vegetarian", "Cheap", "Healthy"]},
	"chickenStirFry" : {
		name: "Chicken Stir Fry",
		id: "chickenStirFry",
		imgSrc: "images/chickenStirFry.jpg",
		cookTime: "25 minutes",
		calories: "470 caories",
		tags: ["", "Asian", "Healthy"]},
}

export default recipes